Repository AY2425S2-CS2113-F11-2/tp, pull requests merged in 2025-04, with the labels that each got.

#74 Dg ppp
  category_summary.txt
  docs/DeveloperGuide.md
  docs/diagrams/ExpenseCRUDFeatureSequenceDiagram.drawio.png
  docs/team/matthew.md
  monthly_summary.txt
  src/main/java/seedu/OMPM.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/currency/Currency.java
  src/main/java/seedu/duke/expense/BudgetManager.java
  src/main/java/seedu/duke/menu/HelpPage.class
  src/main/java/seedu/duke/menu/HelpPage.java
  src/main/java/seedu/duke/messages/Messages.java
  src/main/java/seedu/duke/summary/Categories.java
  src/main/java/seedu/duke/summary/ExpenseClassifier.java
  src/main/java/seedu/duke/ui/UI.java
  src/test/java/seedu/duke/commands/ExpenseCommands.java
Labels: priority.High, type.Task

#81 Add more Javadoc comments to authored code
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/Commands.java
  src/main/java/seedu/duke/storage/DataStorage.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.Low

#82 Add 5. Appendix section to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#85 changes change currency to be more readable
  src/main/java/seedu/duke/currency/Currency.java
Labels: priority.Low

#101 Add new command: sort-list
  docs/UserGuide.md
  docs/diagrams/ExpenseCRUDFeatureSequenceDiagram.drawio.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/Commands.java
  src/main/java/seedu/duke/commands/ExpenseCommand.java
  src/main/java/seedu/duke/expense/BudgetManager.java
  src/main/java/seedu/duke/messages/Messages.java
  src/main/java/seedu/duke/ui/UI.java
  src/test/java/seedu/duke/commands/ExpenseCommands.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Task

#164 Update UG, DG and CRUD Sequence Diagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExpenseCRUDFeatureSequenceDiagram.drawio.png
  docs/team/matthewyeo1.md
  src/main/java/seedu/duke/commands/ExpenseCommand.java
  src/main/java/seedu/duke/messages/Messages.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#168 Add overall program flow chart
  docs/DeveloperGuide.md
  docs/diagrams/ApplicationFlowChart.drawio.png
  docs/team/matthewyeo1.md
Labels: priority.Low, type.Task

#169 Update user stories table in DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Task
