Repository AY2425S2-CS2113-F11-2/tp, pull requests merged in 2025-03, with the labels that each got.

#53 Slight refactor to codebase
  groups.txt
  src/main/java/seedu/duke/commands/ExpenseCommand.java
  src/main/java/seedu/duke/friends/Group.java
  src/main/java/seedu/duke/friends/GroupManager.java
  src/main/java/seedu/duke/messages/Messages.java
  src/main/java/seedu/duke/ui/UI.java
  testOwedAmounts.txt
  text-ui-test/ACTUAL.TXT
Labels: priority.Low

#56 Add date field (mandatory) and update text UI tests and JUnit tests
  src/main/java/seedu/duke/commands/ExpenseCommand.java
  src/main/java/seedu/duke/expense/BudgetManager.java
  src/main/java/seedu/duke/expense/Expense.java
  src/main/java/seedu/duke/storage/DataStorage.java
  src/test/java/seedu/duke/commands/ExpenseCommands.java
  src/test/java/seedu/duke/commands/SplitCommandTest.java
  src/test/java/seedu/duke/expense/BudgetManagerTest.java
  src/test/java/seedu/duke/storage/DataStorageTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#64 Add New Commands to UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  groups.txt
  src/main/java/seedu/duke/commands/Commands.java
  src/main/java/seedu/duke/commands/ExpenseCommand.java
  src/main/java/seedu/duke/menu/HelpPage.java
  src/main/java/seedu/duke/ui/UI.java
  src/test/java/seedu/duke/commands/FriendsCommandTest.java
  testOwedAmounts.txt
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#67 Add XCharts data viz
  build.gradle
  category_summary.txt
  monthly_summary.txt
  src/main/java/seedu/duke/commands/ExpenseCommand.java
  src/main/java/seedu/duke/summary/ExpenseClassifier.java
  src/test/java/seedu/duke/commands/ExpenseCommands.java
Labels: priority.High, type.Enhancement

#69 updates UG, standardizes format, adds j-unit-test
  currentCurrency
  docs/UserGuide.md
  src/main/java/seedu/duke/currency/Currency.java
  src/main/java/seedu/duke/expense/Expense.java
  src/test/java/seedu/duke/commands/ExpenseCommands.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
Labels: priority.High
